services:
    flux_se.sylius_payum_monetico.provider.reference:
        class: FluxSE\SyliusPayumMoneticoPlugin\Provider\ReferenceProvider

    flux_se.sylius_payum_monetico.provider.comment:
        class: FluxSE\SyliusPayumMoneticoPlugin\Provider\CommentProvider

    flux_se.sylius_payum_monetico.provider.address:
        class: FluxSE\SyliusPayumMoneticoPlugin\Provider\AddressProvider

    flux_se.sylius_payum_monetico.provider.context:
        class: FluxSE\SyliusPayumMoneticoPlugin\Provider\ContextProvider
        arguments:
            - "@flux_se.sylius_payum_monetico.provider.address"